### PR TITLE
Add dobby and rubocop fixes

### PR DESCRIPTION
**Pull request by punitcse**
- add dobby action.
- fix rubocop issues.

### CODE REVIEW

**Comment by punitcse** [comment]
> /dobby version patch

Pull request comment event does not trigger unless the workflow merged https://github.community/t/on-issue-comment-events-are-not-triggering-workflows/16784/4

**Review by moltenice — COMMENTED** [review]
How come so many files have been changed?

**Comment by punitcse** [comment]
> How come so many files have been changed?

Rubocop is failing because simplycop is updated. So I also fixed those.

**Review by moltenice — APPROVED** [review]
🧝

**Pull request merged**
